serializers not working
weckoe/schoole_system pull request #1
Opened 2022-02-10 09:21 UTC by weckoe

2022-02-10 11:27 UTC, NickBlackLion commented on schoole_system/authentication/models.py
>  class UserManager(BaseUserManager):
validation needs to be moved to serializer

2022-02-10 11:27 UTC, NickBlackLion commented on schoole_system/authentication/views.py
> +class UserViewSet(viewsets.ViewSet):
Could you please list benefits in using ViewSet vs APIView?

2022-02-10 11:27 UTC, NickBlackLion commented on schoole_system/authentication/views.py
> +            queryset, _ = User.objects.filter(id=user_id).update(**request.data)
strange parsing because id goes to params too but it shouldn't

2022-02-10 11:27 UTC, NickBlackLion commented on schoole_system/authentication/views.py
> +            queryset, _ = User.objects.get_or_create(**request.data)
you need to choose one strategy or create using model or serializer

2022-02-10 11:27 UTC, NickBlackLion commented on schoole_system/authentication/serializers.py
> +            'first_name': {'write_only': True},
why first_name and last_name are read only here?

2022-02-17 10:26 UTC, NickBlackLion commented
Название ПР прям вообще крутое. что команда из названия должна понять? что ты сделал ПР в котором не пашут сериалайзеры?

2022-02-17 10:27 UTC, NickBlackLion commented
почему у тебя структура проекта странная. есть папка с таким же название как проект и только в ней лежит manage.py. почему?

2022-02-17 10:28 UTC, NickBlackLion commented
проект не запускается командой docker compose up -d --build у меня локально. почему?

2022-02-17 10:34 UTC, NickBlackLion requested changes

2022-02-17 10:34 UTC, NickBlackLion commented on requirements.txt
>  psycopg2==2.9.3
у меня локально не устанавливается эта либа

2022-02-17 10:34 UTC, NickBlackLion commented on schoole_system/authentication/models.py
>  class UserManager(BaseUserManager):
так и не перенс валидацию в сериалайзер

2022-02-17 10:34 UTC, NickBlackLion commented on schoole_system/authentication/serializers.py
> +    def validate_email(self, data):
теоретически если ты поставишь в можели поле  ``unique`` эту валидацию делать не надо

2022-02-17 10:34 UTC, NickBlackLion commented on schoole_system/authentication/urls.py
> +urlpatterns = [
почему пути не по РЕСТу?

2022-02-17 10:34 UTC, NickBlackLion commented on schoole_system/authentication/views.py
> +        if request.method == "GET":
Если используешь контроллеры на основе классов метод проверять не надо

2022-02-17 10:34 UTC, NickBlackLion commented on schoole_system/authentication/views.py
> +class UserCreate(CreateAPIView):
почему под это отдельные контроллеры?

2022-02-17 10:39 UTC, NickBlackLion commented on schoole_system/authentication/models.py
> +from authentication.validators import user_image_resolution_check
пути должны быть абсолютными, а у тебя относительные везде
![Screen Shot 2022-02-17 at 1 38 39 PM](https://user-images.githubusercontent.com/22809564/154458920-77db4cfc-2c72-438f-a930-2fef03eeb8cc.png)

2022-02-19 16:21 UTC, weckoe commented on schoole_system/authentication/models.py
> +from authentication.validators import user_image_resolution_check
![Снимок экрана от 2022-02-19 19-20-34](https://user-images.githubusercontent.com/73819883/154809322-36cfa179-4553-46ca-8418-17f724bf0f89.png)
![Снимок экрана от 2022-02-19 19-20-45](https://user-images.githubusercontent.com/73819883/154809324-51b6f28c-9246-494f-b7f6-15b6393b109d.png)
у меня вот так вот, почему-то

2022-02-20 13:24 UTC, weckoe commented
> почему у тебя структура проекта странная. есть папка с таким же название как проект и только в ней лежит manage.py. почему?

а я могу сейчас переименовать папку с manage.py?

2022-02-21 10:04 UTC, NickBlackLion approved these changes

2022-02-21 10:04 UTC, NickBlackLion commented on schoole_system/authentication/serializers.py
> +    password2 = serializers.CharField(write_only=True, required=True)
почему не добавил валидатор сюда?

2022-02-21 10:04 UTC, NickBlackLion commented on schoole_system/authentication/views.py
> +            queryset, many=True
many=True не нужно ессли ты берешь конкретного пользователя

2022-02-21 10:04 UTC, NickBlackLion commented on schoole_system/authentication/views.py
> +        queryset = User.objects.filter(id=pk)
и тут лучше иcпользовать [get_object_or_404](https://docs.djangoproject.com/en/4.0/topics/http/shortcuts/#get-object-or-404)

2022-02-21 10:04 UTC, NickBlackLion commented on schoole_system/authentication/views.py
> +        queryset = User.objects.filter(id=pk)
и дальше в контроллерах

2022-02-21 18:36 UTC, merged